name: Debt Optimizer CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'cloud_functions/debt_optimizer/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'cloud_functions/debt_optimizer/**' ]

env:
  GCP_PROJECT_ID: fiscal-fox-fin
  PYTHON_VERSION: 3.9
  WORKING_DIRECTORY: cloud_functions/debt_optimizer

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('cloud_functions/debt_optimizer/**/requirements*.txt') }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run linting
      run: |
        flake8 src/ tests/ --max-line-length=88 --exclude=__pycache__
        black --check src/ tests/
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./cloud_functions/debt_optimizer/coverage.xml

  deploy-infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy BigQuery resources
      run: |
        chmod +x scripts/create_bigquery_tables.sh
        ./scripts/create_bigquery_tables.sh
    
    - name: Deploy Cloud Functions
      run: |
        chmod +x scripts/deploy_functions.sh
        ./scripts/deploy_functions.sh

  deploy-container:
    needs: [test, deploy-infrastructure]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/debt-optimizer:${{ github.sha }} -f docker/Dockerfile .
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/debt-optimizer:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy debt-optimizer-service \
          --image gcr.io/${{ env.GCP_PROJECT_ID }}/debt-optimizer:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars ENV=production
