name: Debt Optimizer CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'cloud_functions/debt_optimizer/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'cloud_functions/debt_optimizer/**' ]

env:
  GCP_PROJECT_ID: fiscal-fox-fin
  PYTHON_VERSION: 3.9
  WORKING_DIRECTORY: cloud_functions/debt_optimizer

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run linting
      run: |
        flake8 src/ tests/ --max-line-length=88 --exclude=__pycache__
        black --check src/ tests/
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src/

  deploy-infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy BigQuery resources
      run: |
        chmod +x scripts/create_bigquery_tables.sh
        ./scripts/create_bigquery_tables.sh
    
    - name: Deploy Cloud Functions
      run: |
        chmod +x scripts/deploy_functions.sh
        ./scripts/deploy_functions.sh

